# Generated by Django 5.1 on 2026-05-12 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIFaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Otázka")),
                ("definition", models.TextField(verbose_name="Odpověď")),
                (
                    "learn_more_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Štítek odkazu"
                    ),
                ),
                (
                    "learn_more_url",
                    models.URLField(blank=True, verbose_name="Více informací — URL"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Material ikona"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ položka",
                "verbose_name_plural": "FAQ",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Předmět"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Komentář")),
                (
                    "page_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="URL stránky"
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        choices=[("up", "Pomohlo"), ("down", "Nepomohlo")],
                        default="up",
                        max_length=10,
                        verbose_name="Hodnocení",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback od uživatelů",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="AINastroj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Název")),
                (
                    "kategorie",
                    models.CharField(
                        default="Ostatní",
                        help_text="Např. Copilot, Chat, Agent, Specializovaný, Vzdělávání",
                        max_length=50,
                        verbose_name="Kategorie",
                    ),
                ),
                ("kratky_popis", models.TextField(verbose_name="Krátký popis")),
                (
                    "pouziti",
                    models.TextField(blank=True, verbose_name="K čemu se hodí (HTML)"),
                ),
                (
                    "limity",
                    models.TextField(
                        blank=True, verbose_name="Limity a varování (HTML)"
                    ),
                ),
                (
                    "pristup",
                    models.TextField(
                        blank=True, verbose_name="Jak požádat o přístup (HTML)"
                    ),
                ),
                (
                    "ikona_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Cesta k ikoně"
                    ),
                ),
                (
                    "link_pristup_label",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Štítek odkazu — Přístup",
                    ),
                ),
                (
                    "link_pristup_url",
                    models.URLField(blank=True, verbose_name="Odkaz — Přístup"),
                ),
                (
                    "link_navod_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Štítek odkazu — Návod"
                    ),
                ),
                (
                    "link_navod_url",
                    models.URLField(blank=True, verbose_name="Odkaz — Návod"),
                ),
                (
                    "data_level",
                    models.CharField(
                        choices=[
                            ("green", "Zelená — OK i pro citlivá data"),
                            ("yellow", "Žlutá — jen interní / veřejná"),
                            ("red", "Červená — jen veřejná data"),
                        ],
                        default="yellow",
                        max_length=20,
                        verbose_name="Úroveň dat (semafor)",
                    ),
                ),
                (
                    "tagy",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Tagy (oddělené čárkami)",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI nástroj",
                "verbose_name_plural": "AI nástroje",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AINovinka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titulek")),
                ("perex", models.TextField(verbose_name="Perex")),
                ("body", models.TextField(blank=True, verbose_name="Tělo článku")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kategorie"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Internal", "PPF (interní)"),
                            ("External", "Svět (externí)"),
                        ],
                        default="Internal",
                        max_length=20,
                        verbose_name="Zdroj",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Datum publikace",
                    ),
                ),
                (
                    "link1_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Odkaz 1 — štítek"
                    ),
                ),
                (
                    "link1_url",
                    models.URLField(blank=True, verbose_name="Odkaz 1 — URL"),
                ),
                (
                    "link2_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Odkaz 2 — štítek"
                    ),
                ),
                (
                    "link2_url",
                    models.URLField(blank=True, verbose_name="Odkaz 2 — URL"),
                ),
                (
                    "article_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Celý článek — štítek"
                    ),
                ),
                (
                    "article_url",
                    models.URLField(blank=True, verbose_name="Celý článek — URL"),
                ),
            ],
            options={
                "verbose_name": "Novinka",
                "verbose_name_plural": "Novinky",
                "ordering": ["-publish_date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AIPravidlo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Název pravidla"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Popis / pro koho platí"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("green", "Zelená — OK"),
                            ("yellow", "Žlutá — pozor"),
                            ("red", "Červená — zákaz"),
                        ],
                        default="green",
                        max_length=10,
                        verbose_name="Semafor",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Název nástroje"
                    ),
                ),
                (
                    "tool_icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ikona nástroje"
                    ),
                ),
                (
                    "link1_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Štítek odkazu"
                    ),
                ),
                ("link1_url", models.URLField(blank=True, verbose_name="Odkaz")),
            ],
            options={
                "verbose_name": "Pravidlo (semafor)",
                "verbose_name_plural": "Pravidla (semafor)",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AISlovnicekTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Pojem")),
                ("definition", models.TextField(verbose_name="Definice")),
                (
                    "learn_more_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Štítek odkazu"
                    ),
                ),
                (
                    "learn_more_url",
                    models.URLField(blank=True, verbose_name="Odkaz — Více informací"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Material ikona"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pojem ve slovníčku",
                "verbose_name_plural": "Slovníček (pojmy)",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIZdroj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Název")),
                ("description", models.TextField(verbose_name="Popis")),
                (
                    "category",
                    models.CharField(
                        default="Kurz",
                        help_text="Např. Kurz, Platform, Dokumentace, Návod, Agent",
                        max_length=50,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Provozovatel / autor"
                    ),
                ),
                (
                    "url_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Štítek odkazu"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "icon_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Material ikona"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=300, verbose_name="Tagy"),
                ),
            ],
            options={
                "verbose_name": "Vzdělávací zdroj",
                "verbose_name_plural": "Vzdělávací zdroje",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulek")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titulek (EN)"
                    ),
                ),
                (
                    "guide_slug",
                    models.SlugField(max_length=100, verbose_name="Slug průvodce"),
                ),
                (
                    "guide_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Název průvodce"
                    ),
                ),
                (
                    "guide_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Název průvodce (EN)"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero (úvod)"),
                            ("intro", "Intro odstavec"),
                            ("section", "Sekce s nadpisem"),
                            ("highlight", "Zvýrazněný box"),
                            ("steps", "Kroky"),
                            ("conclusion", "Závěr"),
                        ],
                        default="section",
                        max_length=20,
                        verbose_name="Typ sekce",
                    ),
                ),
                ("content", models.TextField(verbose_name="Obsah")),
                ("content_en", models.TextField(blank=True, verbose_name="Obsah (EN)")),
                (
                    "variant",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Variant (kontext)"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="URL obrázku"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Material ikona"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Koncept"), ("Published", "Publikováno")],
                        default="Published",
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide sekce",
                "verbose_name_plural": "Guides — sekce průvodců",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Zasada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Zásada")),
                ("description", models.TextField(verbose_name="Popis")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANO", "ANO — jdi do toho"),
                            ("POZOR", "POZOR — opatrně"),
                            ("NE", "NE — radši ne"),
                        ],
                        default="ANO",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="URL obrázku"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zásada AI",
                "verbose_name_plural": "Zásady (ANO/POZOR/NE)",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIUseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Pořadí")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivní"),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upraveno"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Vytvořeno"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Název use-case"),
                ),
                (
                    "cinnost",
                    models.CharField(
                        max_length=100, verbose_name="Činnost (sumarizace, překlad, …)"
                    ),
                ),
                ("naklik", models.TextField(verbose_name="Krátký popis / náklik")),
                ("postup", models.TextField(blank=True, verbose_name="Postup (HTML)")),
                ("prompt", models.TextField(blank=True, verbose_name="Hotový prompt")),
                (
                    "varovani",
                    models.TextField(blank=True, verbose_name="Varování / pozor na"),
                ),
                (
                    "ocekavany_vystup",
                    models.TextField(blank=True, verbose_name="Očekávaný výstup"),
                ),
                (
                    "kdyz_nefunguje",
                    models.TextField(blank=True, verbose_name="Když to nefunguje"),
                ),
                (
                    "komu_napsat",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Komu napsat (e-mail)"
                    ),
                ),
                (
                    "success_rate",
                    models.CharField(
                        choices=[
                            ("Vysoká", "Vysoká"),
                            ("Střední", "Střední"),
                            ("Nízká", "Nízká"),
                        ],
                        default="Střední",
                        max_length=20,
                        verbose_name="Spolehlivost",
                    ),
                ),
                (
                    "gif_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="URL ukázkového GIFu"
                    ),
                ),
                (
                    "alternativy",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alt_use_cases",
                        to="portal.ainastroj",
                        verbose_name="Alternativní nástroje",
                    ),
                ),
                (
                    "nastroj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="use_cases",
                        to="portal.ainastroj",
                        verbose_name="Doporučený nástroj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Use-case",
                "verbose_name_plural": "Use-cases",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
    ]
